### ISSUE TITLE
X!Tandem score is hyperscore instead of e-value

### ISSUE THREAD

**Issue by tivdnbos** [compomics/psm_utils#55]
In X!Tandem, the scoring scheme is the hyperscore. In the XTandemReader, however, the e-value was assigned (`score=-np.log(peptide_entry["expect"])`). The hyperscore is currently listed in the metadata.

**Comment by RalfG** [comment]
Hi Tim! I guess it really depends on what you want to do with the PSMs downstream on whether you would use the e-value or a hyperscore. I added a new argument to the XTandemReader 'score_key` to give the user the option to choose. (#57)
